daily_digest_job:
  cron: "0 0 * * *"
  class: "DailyDigestJob"
  queue: default

new_answer_job:
  cron: "0 0 * * *"
  class: "NewAnswerJob"
  queue: default

sphinx_index_job:
  cron: "*/30 * * * *"
  class: "SphinxIndexJob"
  queue: default
